### ISSUE TITLE
Missing Celsius unit in Weather Card

### ISSUE THREAD

**Issue by homelab-addict** [vlfldr/homey#6]
Hello! First of all, I would like to say that this project looks amazing and has great potential to evolve over time, as more and more features are added. I would like to ask whether a feature for selecting the units of measurement in the Weather card is in the works. If not, would it be possible for such an option to be added? Thanks!

**Comment by vlfldr** [comment]
Good suggestion. Added a new backend (.env) option HOMEY_API_WEATHER_UNITS. Should work as soon as you pull the updated Docker image or repo. Valid options are `standard` and `metric`. This information has also been added to the options table in README.md. Thank you!
